---
- name: Use the scret file
  hosts: web
  vars_files:
          - secret
  tasks:
          - name: install the mariadb
            service: mariadb
            state: started
            sudo: yes
            
   tasks:
     - name: Check the status of service
       command: systemctl status "{{ item }}
       with_items:
         - sssd
         - sshd
         - httpd
